name: Backend CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-testing:
    name: create environment and run backend tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin_test
          POSTGRES_PASSWORD: password_test
          POSTGRES_DB: hybrid_test_db
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma client
        run: npx prisma generate
        env: 
            DATABASE_URL: postgresql://admin_test:password_test@localhost:5432/hybrid_test_db?schema=public
      - name: Generate Mock ENV
        run: echo "DATABASE_URL=postgresql://admin_test:password_test@localhost:5432/hybrid_test_db?schema=public" > .env.test
      - name: Sync Prisma schema with database
        run: npx prisma db push
        env:
          DATABASE_URL: postgresql://admin_test:password_test@localhost:5432/hybrid_test_db?schema=public
      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: postgresql://admin_test:password_test@localhost:5432/hybrid_test_db?schema=public
